import LocalizedStrings from 'react-native-localization';
const Languages = new LocalizedStrings({
  en: {
    Fun_Do_Notes: 'Fun Do Notes',
    Notes: 'Notes',
    Reminder: 'Reminder',
    Create_New_Label: 'Create new label',
    Archive: 'Archive',
    Deleted: 'Deleted',
    Settings: 'Settings',
    Help_And_Feedback: 'Help & feedback',
    Labels: 'Labels',
    Edit: 'edit',
    Choose_Language: 'Choose Language',
    English: 'English',
    Hindi: 'Hindi',
    Search: 'Search',
    Pinned: 'Pinned',
    Others: 'Others',
    Title: 'Title',
    Note: 'Note',
    Delete: 'Delete',
    Make_A_Copy: 'Make a copy',
    Send: 'Send',
    Collaborator: 'Collaborator',
    Edited: 'Edited',
    Search_Your_Notes: 'Search your notes',
    Logout: 'Logout',
    Camera: 'Camera',
    Galary: 'Galary',
    Later_Today: 'Later today',
    Tomorrow_Morning: 'Tomorrow morning',
    Choose_A_Date: 'Choose a date',
    Choose_A_Time: 'Choose a time',
    Choose_A_Place: 'Choose a place',
    Edit_Labels: 'Edit Labels',
  },
  hin: {
    Fun_Do_Notes: 'फन डू नोट्स',
    Notes: 'नोट्स',
    Reminder: 'रिमाइंडर',
    Create_New_Label: 'नया लेबल बनाएं',
    Archive: 'आर्काइव',
    Deleted: 'हटाए गए',
    Settings: 'सेटिंग',
    Help_And_Feedback: 'हेल्प एंड फीडबैक',
    Labels: 'लेबल',
    Edit: 'एडीट',
    Choose_Language: 'भाषा चुनें',
    English: 'इंग्लिश',
    Hindi: 'हिंदी',
    Search: 'सर्च',
    Pinned: 'पिन की गई',
    Others: 'अन्य',
    Title: 'टाइटल',
    Note: 'नोट',
    Delete: 'हटाना',
    Make_A_Copy: 'एक प्रतिलिपि बना लो',
    Send: 'भेजना',
    Collaborator: 'सहयोगी',
    Edited: 'एडीटेड',
    Search_Your_Notes: 'अपने नोट्स खोजें',
    Logout: 'लॉगआउट',
    Camera: 'कैमरा',
    Galary: 'गेलरी',
    Later_Today: 'आज बाद में',
    Tomorrow_Morning: 'कल सुबह',
    Choose_A_Date: 'कोई तारीख चुनें',
    Choose_A_Time: 'एक समय चुनें',
    Choose_A_Place: 'कोई स्थान चुनें',
    Edit_Labels: 'एडीट लेबल',
  },
});
export default Languages;
