export const Color = {
  HEADING: '#000000',
  PRIMARY: '#ffffff',
  PLACE_HOLDER_COLOR: '#808080',
  LINK: '#1e90ff',
  SECONDARY: '#87ceeb',
  TINT: '#000000aa',
};
export const Padding = {
  PADDING_ONE: 5,
  PADDING_TWO: 7,
  PADDING_THREE: 8,
  PADDING_FOUR: 10,
  PADDING_FIVE: 15,
  PADDING_SIX: 20,
  PADDING_SEVEN: 25,
  PADDING_EIGHT: 30,
  PADDING_NINE: 35,
  PADDING_TEN: 40,
  PADDING_ELEVEN: 45,
  PADDING_TWELVE: 50,
  PADDING_THIRTEEN: 160,
};
export const Margin = {
  MARGIN_ONE: '2.5%',
  MARGIN_TWO: 5,
  MARGIN_THREE: 7,
  MARGIN_FOUR: 8,
  MARGIN_FIVE: 10,
  MARGIN_SIX: 15,
  MARGIN_SEVEN: 20,
  MARGIN_EIGHT: 25,
  MARGIN_NINE: 30,
  MARGIN_TEN: 35,
  MARGIN_ELEVEN: 40,
  MARGIN_TWELVE: 45,
  MARGIN_THIRTEEN: 50,
};
export const Icon = {
  SIZE_ONE: 15,
  SIZE_TWO: 20,
  SIZE_THREE: 25,
  SIZE_FOUR: 40,
};
export const BorderRadius = {
  RADIUS_ONE: 30,
  RADIUS_TWO: 15,
  RADIUS_THREE: 20,
};
export const Border = {
  BORDER_RADIUS: 10,
  ROUND_CORNER: 20,
  BUTTON_BORDER: 10,
};
export const Font = {
  PRIMARY: 20,
  SECONDARY: 15,
  LARGE: 25,
  EXTRA_LARGE: 35,
  MEDIUM: 18,
  SMALL: 13,
};
export const Flex = {
  ONE: 1,
  TWO: 2,
  THREE: 3,
};
